### ISSUE TITLE
Not running on my Win 10

### ISSUE THREAD

**Issue by mijnmodelbaan** [andreaskielkopf/TasmoView#2]
Hello Andreas,

Just tried your TasmoView on my Win 10 system to no avail. Updated my Java to latest version but still an error message stating:

>D:\PlatformIO\Projects>java -jar TasmoView.jar
>Error: A JNI error has occurred, please check your installation and try again
>Exception in thread "main" java.lang.UnsupportedClassVersionError: >de/uhingen/kielkopf/andreas/tasmoview/TasmoView has been compiled by a more recent version >of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class >file versions up to 52.0
>        at java.lang.ClassLoader.defineClass1(Native Method)
>        at java.lang.ClassLoader.defineClass(Unknown Source)
>        at java.security.SecureClassLoader.defineClass(Unknown Source)
>        at java.net.URLClassLoader.defineClass(Unknown Source)
>        at java.net.URLClassLoader.access$100(Unknown Source)
>        at java.net.URLClassLoader$1.run(Unknown Source)
>        at java.net.URLClassLoader$1.run(Unknown Source)
>        at java.security.AccessController.doPrivileged(Native Method)
>        at java.net.URLClassLoader.findClass(Unknown Source)
>        at java.lang.ClassLoader.loadClass(Unknown Source)
>        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>        at java.lang.ClassLoader.loadClass(Unknown Source)
>        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

I have Java version:

![image](https://user-images.githubusercontent.com/31405979/72794074-ae1b8e80-3c3b-11ea-882b-2db3b61427d8.png)

**Comment by andreaskielkopf** [comment]
So you have Java 8. :-( But you need java11 or greater

**Comment by andreaskielkopf** [comment]
you may get it at https://www.oracle.com/technetwork/java/javase/downloads/index.html
or https://jdk.java.net/ or https://jdk.java.net/13/

**Comment by andreaskielkopf** [comment]
With this new Version 0.4 you could try it again. TasmoView now works even with Java 8
